import ctaList from './types/ctaList'
import colorSwatch from './types/colorSwatch'
import footer from './types/footer'
import footerDetail from './types/footerDetail'
import footerDetails from './types/footerDetails'
import globalComponentList from './types/globalComponentList'
import header from './types/header'
import hero from './types/hero'
import layout from './types/layout'
import link from './types/link'
import page from './types/page'
import pageComponentList from './types/pageComponentList'
import projects from './types/projects'
import tag from './types/tag'
import mission from './types/mission'
import missionCard from './types/missionCard'
import specialProjects from './types/specialProjects'
import contactCta from './types/contactCta'
import section from './types/section'
import imageCard from './types/components/carousel'
import imageCarousel from './types/components/imageCarousel'
import captionCarousel from './types/components/captionCarousel'
import annotationImage from './types/components/annotationImage'
import imageHotspot from './types/components/imageHotspot'
import imageExpandableCaption from './types/components/imageExpandableCaption'
import spot from './types/components/spot'

export const schema = {
  types: [page, layout, header, ctaList, link, pageComponentList, hero, globalComponentList, footer, footerDetails, footerDetail, colorSwatch, projects, tag, mission, missionCard, specialProjects, contactCta, section, imageCard, imageCarousel, captionCarousel, annotationImage, imageHotspot, imageExpandableCaption, spot],
}
